/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import javax.swing.*;
/**
 *
 * @author 
 */

public class ventana2 extends javax.swing.JFrame {

    private String user = "usuario";
    private String pass = "contrasena";
    
    /**
     * Creates new form interfaz
     */

    public ventana2() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setResizable(false);
        this.setTitle("TIPO DE USUARIO: REGISTRADO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PUBuserData = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        PUBpassData = new javax.swing.JPasswordField();
        passLabel = new javax.swing.JLabel();
        BotExit = new javax.swing.JButton();
        BotBack = new javax.swing.JButton();
        infoVentana = new javax.swing.JLabel();
        BotAcept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PUBuserData.setBackground(new java.awt.Color(0, 51, 153));
        PUBuserData.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        PUBuserData.setForeground(new java.awt.Color(255, 255, 255));
        PUBuserData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUBuserDataActionPerformed(evt);
            }
        });
        getContentPane().add(PUBuserData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 400, 40));

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("Nombre de usuario:");
        getContentPane().add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 225, 240, 40));

        PUBpassData.setBackground(new java.awt.Color(0, 51, 153));
        PUBpassData.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PUBpassData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 400, 40));

        passLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        passLabel.setForeground(new java.awt.Color(255, 255, 255));
        passLabel.setText("Contraseña:");
        getContentPane().add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 150, -1));

        BotExit.setBackground(new java.awt.Color(255, 0, 0));
        BotExit.setForeground(new java.awt.Color(255, 255, 255));
        BotExit.setText("Salir");
        BotExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotExitActionPerformed(evt);
            }
        });
        getContentPane().add(BotExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        BotBack.setBackground(new java.awt.Color(0, 51, 153));
        BotBack.setForeground(new java.awt.Color(255, 255, 255));
        BotBack.setText("Volver");
        BotBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotBackActionPerformed(evt);
            }
        });
        getContentPane().add(BotBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        infoVentana.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        infoVentana.setForeground(new java.awt.Color(255, 255, 255));
        infoVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoVentana.setText("USUARIO: CIVIL");
        getContentPane().add(infoVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 720, -1));

        BotAcept.setText("Aceptar");
        BotAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAceptActionPerformed(evt);
            }
        });
        getContentPane().add(BotAcept, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotExitActionPerformed

        int accion = JOptionPane.showConfirmDialog(null,"Seguro que desea salir del programa?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == accion){
        System.exit(0);
        }else{
        this.setVisible(true);
        }
    }//GEN-LAST:event_BotExitActionPerformed

    private void BotBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotBackActionPerformed
        principal ventPrincipal = new principal();
        ventPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotBackActionPerformed

    private void BotAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAceptActionPerformed

        String verifyUser = PUBuserData.getText();
        String verifyPass = PUBpassData.getText();
        
        //FUNCION DE VERIFICACION DE CAMPOS COMPLETOS
        if(verifyUser.equals("") && verifyPass.equals("")){
        JOptionPane.showMessageDialog(null, "Ambos campos deben estar completos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else
        //FUNCION DE VERIFICACION DE USUARIO Y CONTRASEÑA
        if(verifyUser.equals(user) && verifyPass.equals(pass)){
        ventana1 PublicUser = new ventana1();
        PublicUser.setVisible(true);
        this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Nombre de usuario o contraseña incorrectos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotAceptActionPerformed

    private void PUBuserDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUBuserDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PUBuserDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAcept;
    private javax.swing.JButton BotBack;
    private javax.swing.JButton BotExit;
    private javax.swing.JPasswordField PUBpassData;
    private javax.swing.JTextField PUBuserData;
    private javax.swing.JLabel infoVentana;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
