/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import javax.swing.*;
import usuarios.tipoUsuario;
/**
 *
 * @author 
 */

public class ventana3 extends javax.swing.JFrame {
    
    private String user = "1234567";
    private String pass = "contrasena";

    /**
     * Creates new form ventana3
     */
    
    public ventana3() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setResizable(false);
        this.setTitle("TIPO DE USUARIO: FUNCIONARIO PUBLICO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoVentana = new javax.swing.JLabel();
        PRIuserData = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        PRIpassData = new javax.swing.JPasswordField();
        BotExit = new javax.swing.JButton();
        BotBack = new javax.swing.JButton();
        BotAcept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoVentana.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        infoVentana.setForeground(new java.awt.Color(255, 255, 255));
        infoVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoVentana.setText("USUARIO: FUNCIONARIO PUBLICO");
        getContentPane().add(infoVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 720, -1));

        PRIuserData.setBackground(new java.awt.Color(0, 51, 153));
        PRIuserData.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PRIuserData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 400, 40));

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("Numero ID:");
        getContentPane().add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        passLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        passLabel.setForeground(new java.awt.Color(255, 255, 255));
        passLabel.setText("Contraseña:");
        getContentPane().add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        PRIpassData.setBackground(new java.awt.Color(0, 51, 153));
        PRIpassData.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PRIpassData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 400, 40));

        BotExit.setBackground(new java.awt.Color(255, 0, 0));
        BotExit.setForeground(new java.awt.Color(255, 255, 255));
        BotExit.setText("Salir");
        BotExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotExitActionPerformed(evt);
            }
        });
        getContentPane().add(BotExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        BotBack.setBackground(new java.awt.Color(0, 51, 153));
        BotBack.setForeground(new java.awt.Color(255, 255, 255));
        BotBack.setText("Volver");
        BotBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotBackActionPerformed(evt);
            }
        });
        getContentPane().add(BotBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BotAcept.setText("Aceptar");
        BotAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAceptActionPerformed(evt);
            }
        });
        getContentPane().add(BotAcept, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotBackActionPerformed
        principal ventPrincipal = new principal();
        ventPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotBackActionPerformed

    private void BotExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotExitActionPerformed

        int accion = JOptionPane.showConfirmDialog(null,"Seguro que desea salir del programa?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == accion){
        System.exit(0);
        }else{
        this.setVisible(true);
        }
    }//GEN-LAST:event_BotExitActionPerformed

    private void BotAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAceptActionPerformed

        String verifyUser = PRIuserData.getText();
        String verifyPass = PRIpassData.getText();
        
        //FUNCION DE VERIFICACION DE CAMPOS COMPLETOS
        if(verifyUser.equals("") && verifyPass.equals("")){
        JOptionPane.showMessageDialog(null, "Ambos campos deben estar completos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else
        //FUNCION DE VERIFICACION DE USUARIO Y CONTRASEÑA    
        if(verifyUser.equals(user) && verifyPass.equals(pass)){
        ventana1 PublicUser = new ventana1();
        PublicUser.setVisible(true);
        this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Nombre de usuario o contraseña incorrectos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotAceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAcept;
    private javax.swing.JButton BotBack;
    private javax.swing.JButton BotExit;
    private javax.swing.JPasswordField PRIpassData;
    private javax.swing.JTextField PRIuserData;
    private javax.swing.JLabel infoVentana;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
